import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider, SignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import Providers from '@/utils/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        elements: {
          formButtonPrimary: 'bg-red-700 hover:bg-red-800',
          footerActionLink: 'text-red-500 hover:text-red-600',
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
